hf_configuration:
  hf_dataset_name: nor_agriculture_bench
  hf_organization: norjordAI
  hf_token: $HF_TOKEN
  private: false 
  upload_card: true
  local_saving: true
  export_jsonl: true
  local_dataset_dir: data/saved
  jsonl_export_dir: data/saved/jsonl

model_list:
  - model_name: norallm/normistral-11b-thinking-gguf
    base_url: http://localhost:8000/v1

pipeline:
  ingestion:
    source_documents_dir: data/raw
    output_dir: data/processed
    upload_to_hub: false
    llm_ingestion: false
    
  summarization:
    max_tokens: 32768
    
  chunking:
    chunking_mode: semantic_chunking
    h_min: 2
    h_max: 5
    num_multihops_factor: 1
  
  single_hop_question_generation:
    question_mode: open-ended 
    additional_instructions: "Lag spørsmål som du ville tenkt på hvis du var bonde. Var spesifikk. Gi et fullstendig svar. Ikke bruk ord NIBIO, NLR, Plantevernleksikonet, kilder, dokumenter"

    
  multi_hop_question_generation:
    question_mode: open-ended
    additional_instructions: "Lag spørsmål som du ville tenkt på hvis du var bonde. Var spesifikk. Gi et fullstendig svar. Ikke bruk ord NIBIO, NLR, Plantevernleksikonet, kilder, dokumenter"

    
  cross_document_question_generation:
    question_mode: open-ended
    additional_instructions: "Lag spørsmål som du ville tenkt på hvis du var bonde. Var spesifikk. Gi et fullstendig svar.  Ikke bruk ord NIBIO, NLR, Plantevernleksikonet, kilder, dokumenter"
    max_combinations: 100
    chunks_per_document: 100
    num_docs_per_combination: [2, 5]
    random_seed: 42
    
  prepare_lighteval:
  
  citation_score_filtering:
    alpha: 0.7
    beta: 0.3

