hf_configuration:
  hf_dataset_name: nor_agriculture_bench
  hf_organization: norjordAI
  hf_token: $HF_TOKEN
  private: false
  upload_card: true
  local_saving: true
  export_jsonl: true
  local_dataset_dir: data/saved
  jsonl_export_dir: data/saved/jsonl

model_list:
  - model_name: norallm/normistral-11b-thinking
    base_url: http://localhost:8000/v1
    max_concurrent_requests: 32

pipeline:
  ingestion:
    source_documents_dir: data/raw
    output_dir: data/processed
    upload_to_hub: false
    llm_ingestion: false

  summarization:
    max_tokens: 16384 
    summarization_user_prompt: prompts/summarization_user_prompt.md
    combine_summaries_user_prompt: prompts/combine_summaries_user_prompt.md

  chunking:
    l_max_tokens: 1024     
    token_overlap: 256

  single_hop_question_generation:
    question_mode: open-ended
    question_schema: schemas/data_output_schema.py.py
    single_hop_system_prompt: prompts/single_hop_system_prompt.md
    
  multi_hop_question_generation:
    question_mode: open-ended
    question_schema: schemas/data_output_schema.py.py
    multi_hop_system_prompt: prompts/multi_hop_system_prompt.md
    
  cross_document_question_generation:
    question_mode: open-ended
    max_combinations: 100 # default is 100
    chunks_per_document: 1 # default is 1
    num_docs_per_combination:
    - 2 # default is 2
    - 5 # default is 5
    

  prepare_lighteval:

  citation_score_filtering:
    alpha: 0.7
    beta: 0.3